### ISSUE TITLE
Cannot find module './components/GDialog.vue' or its corresponding type declarations.

### ISSUE THREAD

**Issue by MIDEV-05** [MichaelGitArt/gitart-vue-dialog#1]
Hi ! Good work on this dialog plugin

I'm facing an issue with the dialog usage !
When i put the following line
`import { GDialog } from "gitart-vue-dialog";`

 in my vue component, i got this error :
 
 `./../common/temp/node_modules/.pnpm/gitart-vue-dialog@1.1.0_vue@3.2.14/node_modules/gitart-vue-dialog/src/index.ts:4:36 - error TS2307: Cannot find module './components/GDialog.vue' or its corresponding type declarations.
4 export { default as GDialog } from './components/GDialog.vue'`

`../../common/temp/node_modules/.pnpm/gitart-vue-dialog@1.1.0_vue@3.2.14/node_modules/gitart-vue-dialog/src/index.ts:9:40 - error TS2307: Cannot find module './components/GDialogRoot.vue' or its corresponding type declarations.
9 export { default as GDialogRoot } from './components/GDialogRoot.vue'`

I'm trying to use the dialog as a standalone component (no plugin)

**Comment by MichaelGitArt** [comment]
Thanks for the issue. I guess because of "export * from '../src/index'", typescript just cannot recognize types from index.upd.d.ts.

Does the dialog not work with this error at all?

Could you upload the entire code base on GitHub and I will check it locally?

**Comment by MichaelGitArt** [comment]
There is type generation (.d.ts) for version 1.2.0+

Try to upgrade. Let me know if that doesn't work
